import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import ToastProvider from "./components/ToastProvider";
import { Mitr } from "next/font/google";

const mitr = Mitr({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["thai", "latin"],
  variable: "--font-mitr",
});

export const metadata = {
  title: "Blog Hoshizora",
  description: "Generated by Jiranon-K",
  icons: {
    icon: [{ url: "/favicon.ico" }],
    apple: [{ url: "/favicon.ico", sizes: "180x180", type: "image/x-icon" }],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${mitr.className} overflow-x-hidden`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          {children}
          <ToastProvider />
        </ThemeProvider>
      </body>
    </html>
  );
}
