import "./globals.css";
import ThemeProvider from './components/ThemeProvider';
import ToastProvider from './components/ToastProvider';

export const metadata = {
  title: "Blog Hoshizora",
  description: "Generated by Jiranon-K",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="overflow-x-hidden" suppressHydrationWarning>
        <ThemeProvider>
          {children}
          <ToastProvider />
        </ThemeProvider>
      </body>
    </html>
  );
}